In [7]:
list = [5, 8, 1, 0, 9]
list[2]

1

In [7]:
list = ["Jimi", 5000, True, 3.8, 2019, 300]
print(list[-1])

300


In [16]:
# Slicing
# Access cross section of Lists 
lst1 = ['Gayle', 'Gilchrist', 'Waugh', 'Dravid', 'Pollock', 'Tendulkar', 'Gavaskar', 'Dhoni']
print(lst1[1:5])    # Print elements 2 to 5
print(lst1[:5])    # Print elements start to 5 - default start 0
print(lst1[-3:-2])    # Print all elements starting from 2nd - default end is all

['Gilchrist', 'Waugh', 'Dravid', 'Pollock']
['Gayle', 'Gilchrist', 'Waugh', 'Dravid', 'Pollock']
['Tendulkar']


In [19]:
num = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(num[1:10:3])

[2, 5, 8]


In [21]:
num = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(num.extend([11, 12, 13]))


None


In [23]:
req=[]
for i in range(1, 100):
    req.append(i)
print(req)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [7]:
a = set([1, 2, 3, 4, 5])
b = set([2, 3, 4, 8, 9])
diff1=b-a
diff2=a.symmetric_difference(b)
print(diff2)

{1, 5, 8, 9}


In [4]:
set1 = set(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
set2 = set(['a', 'b', 'c', 'e', 'f', 'h', 'm', 't', 'q'])
print("Set 1: ", set1)
print("Set 2: ", set2)

Set 1:  {'e', 'c', 'g', 'b', 'f', 'a', 'h', 'd'}
Set 2:  {'e', 'c', 'm', 't', 'b', 'f', 'a', 'h', 'q'}


In [25]:
import numpy as np
import pandas as pd
arr = np.array([[0,5,10,15,20], [2, 4, 6, 8, 10]])
print(arr)
print(arr.shape)

[[ 0  5 10 15 20]
 [ 2  4  6  8 10]]
(2, 5)


In [32]:
# Create an array filled with random values
arr = np.random.random((3,3))  
print(arr)

[[0.46618546 0.66456611 0.13368155]
 [0.24284825 0.13774897 0.75142219]
 [0.95380634 0.48714375 0.87153419]]


In [34]:
arr = np.arange(0, 10, 2)
arr

array([0, 2, 4, 6, 8])

In [47]:
# Reshape the array to a new specified dimension
arr = np.arange(30)
arr = arr.reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])